### ISSUE TITLE
Difficult to understand how to get started

### ISSUE THREAD

**Issue by dgmstuart** [chefy-io/clojure-katas#7]
Hello 

This looks like a great tool, but I'm confused as to how to actually get started with solving Kata:

The readme says:

> arranged-prob is not implemented under /src/clojure_katas/sine_angle.clj:

Is this saying that the first step is to create a new file called arranged-prob.clj? or define a function called arranged-prob in the sine_angle.clj file? arranged-prob seems to be a separate problem and I don't understand how the two are related.

Maybe some more granular instructions would be useful? e.g.
1. Find the next kata with x
2. Run the tests for that kata with x
3. Edit file y to implement the solution

Apologies if these are noob questions - I'm new to Clojure

If I try defining a sine function in src/clojure-koans/sine_angle.clj, and running `lein test test/clojure_katas/sine_angle_test.clj` Then I get the following error:

```
Exception in thread "main" clojure.lang.ExceptionInfo: Unimplemented problem {:symbol clojure-katas.sine-angle/sine}
```

**Comment by marshallshen** [comment]
@dgmstuart Thanks for the feedback! I'm working to smooth out some edges in the repo. I will keep you posted!

Also, any contribution is welcome!

:beers:

**Comment by dgmstuart** [comment]
@marshallshen Glad to hear it :) Very happy to contribute once I have a basic understanding of how the thing works ;)

**Comment by marshallshen** [comment]
Close out since it's out dated.
